-- ======================================================================
-- SMD PRIME - SUPABASE DATABASE ARCHITECTURE & TELEMETRY SCHEMA
-- ======================================================================

-- 1. Users Table (Telegram Profile Synchronization)
CREATE TABLE IF NOT EXISTS public.users (
    telegram_user_id TEXT PRIMARY KEY,
    username TEXT DEFAULT '',
    first_name TEXT DEFAULT '',
    avatar_url TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS & Permissive Access Policy for users
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public select and upsert on users" 
    ON public.users FOR ALL USING (true) WITH CHECK (true);

-- 2. Movie Metadata Table (Dynamic Duration Fetcher & Storer)
CREATE TABLE IF NOT EXISTS public.movie_metadata (
    movie_uid TEXT PRIMARY KEY,
    duration_seconds INTEGER NOT NULL,
    formatted_duration TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS & Permissive Access Policy for movie_metadata
ALTER TABLE public.movie_metadata ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public select and upsert on movie_metadata" 
    ON public.movie_metadata FOR ALL USING (true) WITH CHECK (true);

-- 3. User Watch History Table (Continue Watching Engine)
CREATE TABLE IF NOT EXISTS public.user_watch_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_user_id TEXT NOT NULL,
    movie_uid TEXT NOT NULL,
    progress_seconds INTEGER NOT NULL DEFAULT 0,
    duration_seconds INTEGER NOT NULL DEFAULT 0,
    last_watched_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT user_watch_history_user_movie_key UNIQUE (telegram_user_id, movie_uid)
);

-- Index for fast user watch history lookup sorted by last_watched_at
CREATE INDEX IF NOT EXISTS idx_user_watch_history_lookup 
    ON public.user_watch_history(telegram_user_id, last_watched_at DESC);

-- Enable RLS & Permissive Access Policy for user_watch_history
ALTER TABLE public.user_watch_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public select and upsert on user_watch_history" 
    ON public.user_watch_history FOR ALL USING (true) WITH CHECK (true);

-- 4. Stream Analytics Table (Telemetry Logger)
CREATE TABLE IF NOT EXISTS public.stream_analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_uid TEXT NOT NULL,
    telegram_user_id TEXT NOT NULL,
    quality_watched TEXT NOT NULL DEFAULT '1080p',
    sa_account_index INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for stream telemetry queries
CREATE INDEX IF NOT EXISTS idx_stream_analytics_movie_uid 
    ON public.stream_analytics(movie_uid, created_at DESC);

-- Enable RLS & Permissive Access Policy for stream_analytics
ALTER TABLE public.stream_analytics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public insert and select on stream_analytics" 
    ON public.stream_analytics FOR ALL USING (true) WITH CHECK (true);
