name = "smd-stream-node-3"
main = "worker_sync.js"
compatibility_date = "2026-08-20"

[vars]
GOOGLE_DRIVE_FOLDER_ID = "13QLJomTi-5IA4Jjz7TOMSEKwalE6mSCt"
SUPABASE_URL = "https://iwulcblngplsjtsipods.supabase.co"

[[kv_namespaces]]
binding = "SA_TOKENS"
id = "50dd4f06688c48bc8afeb50cdb68ee9b"