name = "smd-stream-node-1"
main = "worker_sync.js"
compatibility_date = "2026-08-20"

[vars]
STREAM_SECRET = "smd_prime_secure_jwt_secret_key_2026"
GOOGLE_DRIVE_FOLDER_ID = "13QLJomTi-5IA4Jjz7TOMSEKwalE6mSCt"
SUPABASE_URL = "https://iwulcblngplsjtsipods.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3dWxjYmxuZ3Bsc2p0c2lwb2RzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NzA0MTA2MywiZXhwIjoyMTAyNjE3MDYzfQ.X61a2cj17Zs8Q-0-Pe1ku1PMi_uiybIlYFLv61d8tDU"
